# -*-Makefile-*-
#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id$
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/dds/OvernightTests/overnight/ospli/tags/OSPL_V6_8_3-RC5/ubuntu1604-64a/x86_64.linux-release-inner/build/bin/mwc.pl -features ospl_os_host_linux=1 -features ospl_os_linux=1 -features ospl_64_bit=1 -value_template lib_modifier= -include /bin/MakeProjectCreator/config -include /bin/MakeProjectCreator/config/TAO -features x86_64_linux=1 -features ospl_arch_x86_64=1 -type make -features no_c99=0 -features isocpp2_cxx11=1 HDE/x86_64.linux/examples/examples_simple.mwc
#
#----------------------------------------------------------------------------


all: sac_datariverchannel_types sac_datariverchannel_pub sac_datariverchannel_sub sacpp_datariverchannel_types sacpp_datariverchannel_pub sacpp_datariverchannel_sub ISO_Cxx_V2_DataRiverChannel_Types ISO_Cxx_V2_DataRiverChannel_Impl ISO_Cxx_V2_DataRiverChannel_Pub ISO_Cxx_V2_DataRiverChannel_Sub

clean depend generated realclean check-syntax $(CUSTOM_TARGETS):	
    @cd cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_types $(@)
	@cd cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_pub $(@)
	@cd cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_sub $(@)
	
.PHONY: sac_datariverchannel_types
sac_datariverchannel_types:
	@cd DataRiverChannel/c/standalone && $(MAKE) -f Makefile.sac_datariverchannel_types all

.PHONY: sac_datariverchannel_pub
sac_datariverchannel_pub: sac_listener_types
	@cd DataRiverChannel/c/standalone && $(MAKE) -f Makefile.sac_datariverchannel_pub all

.PHONY: sac_datariverchannel_sub
sac_datariverchannel_sub: sac_listener_types
	@cd DataRiverChannel/c/standalone && $(MAKE) -f Makefile.sac_datariverchannel_sub all

.PHONY: sacpp_datariverchannel_types
sacpp_datariverchannel_types:
	@cd DataRiverChannel/cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_types all

.PHONY: sacpp_datariverchannel_pub
sacpp_datariverchannel_pub: sacpp_listener_types
	@cd DataRiverChannel/cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_pub all

.PHONY: sacpp_datariverchannel_sub
sacpp_datariverchannel_sub: sacpp_listener_types
	@cd DataRiverChannel/cpp/standalone && $(MAKE) -f Makefile.sacpp_datariverchannel_sub all

.PHONY: ISO_Cxx_V2_DataRiverChannel_Types
ISO_Cxx_V2_DataRiverChannel_Types:
	@cd DataRiverChannel/isocpp2 && $(MAKE) -f Makefile.ISO_Cxx_V2_DataRiverChannel_Types all

.PHONY: ISO_Cxx_V2_DataRiverChannel_Impl
ISO_Cxx_V2_DataRiverChannel_Impl: ISO_Cxx_V2_Listener_Types
	@cd DataRiverChannel/isocpp2 && $(MAKE) -f Makefile.ISO_Cxx_V2_DataRiverChannel_Impl all

.PHONY: ISO_Cxx_V2_DataRiverChannel_Pub
ISO_Cxx_V2_DataRiverChannel_Pub: ISO_Cxx_V2_Listener_Impl
	@cd DataRiverChannel/isocpp2 && $(MAKE) -f Makefile.ISO_Cxx_V2_DataRiverChannel_Pub all

.PHONY: ISO_Cxx_V2_DataRiverChannel_Sub
ISO_Cxx_V2_DataRiverChannel_Sub: ISO_Cxx_V2_Listener_Impl
	@cd DataRiverChannel/isocpp2 && $(MAKE) -f Makefile.ISO_Cxx_V2_DataRiverChannel_Sub all

project_name_list:
	@echo sac_datariverchannel_pub
	@echo sac_datariverchannel_sub
	@echo sac_datariverchannel_types
	@echo sacpp_datariverchannel_pub
	@echo sacpp_datariverchannel_sub
	@echo sacpp_datariverchannel_types
	@echo ISO_Cxx_V2_DataRiverChannel_Impl
	@echo ISO_Cxx_V2_DataRiverChannel_Pub
	@echo ISO_Cxx_V2_DataRiverChannel_Sub
	@echo ISO_Cxx_V2_DataRiverChannel_Types
